name: build_linux

on: [push, pull_request]

jobs:
  Test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable] # [stable, beta]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: "Install Dependencies"
        run: sudo apt install libdbus-1-dev pkg-config libgtk-3-dev libgdk3.0-cil-dev libsoup2.4-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev -y
      - name: "Install Tauri"
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: tauri-cli
      - name: "Build Tauri App"
        uses: actions-rs/cargo@v1
        with:
          command: tauri
          args: build
      - name: "Collect Artifacts"
        run: |
          mv src-tauri/target/release/taurapp ./taurapp_amd64_linux
          mv src-tauri/target/release/bundle/appimage/*.AppImage ./taurapp_amd64.AppImage
          mv src-tauri/target/release/bundle/deb/*.deb ./taurapp_amd64.deb
      - name: "Upload Build"
        uses: actions/upload-artifact@v2
        with:
          name: taurapp_amd64_linux
          path: taurapp_amd64_linux
          retention-days: 1
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            taurapp_amd64_linux
            taurapp_amd64.AppImage
            taurapp_amd64.deb
